name: Ad Hoc Hockey Message

on:
  workflow_dispatch: # manual
    inputs:
        message:
            description: 'Message to send to Discord'
            required: true
            default: 'Hello from Hockey Bot!'
        webhook:
            description: 'Discord'
            required: true
            default: Test
            type: choice
            options:
            - Test
            - WonderPals
       

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Select enviorment
        run: |
          if [ "${{ github.event.inputs.webhook }}" = "Test" ]; then
            echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.webhook }}" = "WonderPals" ]; then
            echo "DISCORD_WEBHOOK=${{ secrets.WEBHOOK_DISCORD_WONDERPALS_HOCKEY }}" >> $GITHUB_ENV
          else
            echo "Invalid webhook option"
            exit 1
          fi 


      - name: Discord notification
        env:
            DISCORD_WEBHOOK: ${{ env.DISCORD_WEBHOOK }}
            DISCORD_USERNAME: Hockey Bot
            DISCORD_AVATAR: https://preview.redd.it/7vhwwme8t76b1.jpg?width=872&auto=webp&s=75ce72088c5ba239c9bde22f96b5227ece9f6d82
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ github.event.inputs.message }}"
