name: Daily Hockey Message

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch: # manual

jobs:
  daily-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Get schedule
        id: get_schedule
        run: |
          # call your getData() and save to a file
          node -e "require('./src/hockey-bot').getData().then(d=>console.log(d)).catch(err=>{ console.error(err); process.exit(1); })" > schedule.txt
          # expose the file contents as a multiline GitHub Actions output
          echo "schedule<<EOF" >> $GITHUB_OUTPUT
          cat schedule.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Discord notification
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ steps.get_schedule.outputs.schedule }}"
